name: md > html > pdf CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  md-html-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir resume
          cp -ra src/* resume/

      - uses: docker://pandoc/core:2.9
        with:
          args: -c resume/style.css -o resume/index.html resume/resume.md

      - run: |
          sudo apt-get update
          sudo apt-get install xvfb libfontconfig wkhtmltopdf
          wkhtmltopdf -L 20mm -R 20mm resume/index.html resume/resume.pdf
          git config --global user.email "jqocon@gmail.com"
          git config --global user.name "yeikiu"
          git add -A
          git commit -m 'deploy: resume'
          git push origin master