name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: docker://pandoc/core:2.9
      - run: chmod 755 ./pdf-hook.sh
      - run: ./pdf-hook.sh
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output